# Project config
[project]
runner = "openocd"
# args = { conf = [""], build = [""], run = [""], flash = [""] }
default_profile = "sim"

# Build dir config
[build]
root = "build"

# Build profiles
[profile.sim]
board = "qemu_cortex_m3"
# args = { conf = [""], build = [""], run = [""], flash = [""] }

[profile.prod]
board = "nucleo_f439zi"
# args = { conf = [""], build = [""], run = [""], flash = [""] }
